spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer-smart-home
    username: dbuser
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

grpc:
  server:
    port: 9094
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: analyzer-group
    auto-offset-reset: earliest
    enable-auto-commit: false

logging:
  level:
    # Наши классы - подробно
    ru.yandex.practicum: DEBUG
    ru.yandex.practicum.processor: INFO
    ru.yandex.practicum.handler: INFO
    ru.yandex.practicum.repository: INFO

    # Kafka - для отладки
    org.apache.kafka: INFO
    org.springframework.kafka: INFO

    # База данных - видеть SQL запросы
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

    # Spring - общая информация
    org.springframework: INFO

    # gRPC - для отладки коммуникации
    io.grpc: INFO
    net.devh.boot.grpc: INFO

    # Другие библиотеки - только ошибки
    org.hibernate: INFO
    com.zaxxer.hikari: INFO

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"